# Generated by Django 5.0.1 on 2024-01-26 15:00

import django.db.models.deletion
import django_forms_basics.demoapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django_forms_basics.demoapp.validators.validator_only_letters_in_name]),
        ),
        migrations.AddField(
            model_name='client',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demoapp.store'),
        ),
    ]
