# Generated by Django 5.0.1 on 2024-02-03 11:13

import django.core.validators
import django.db.models.deletion
import django_forms_advanced.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django_forms_advanced.core.validators.validate_name])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4), django_forms_advanced.core.validators.validate_name])),
                ('age', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
