# Generated by Django 5.0.1 on 2024-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='core/users_profile_images'),
        ),
    ]
